name: Build and Release Electron App

# PENGATURAN: Jalan otomatis setiap kali ada push ke branch 'main'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest 
    permissions:
      contents: write 

    steps:
      - name: 1. Mendownload kode dari Repository
        uses: actions/checkout@v4

      - name: 2. Mempersiapkan Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 3. Menginstall Dependencies
        run: npm install

      - name: 4. Build Aplikasi dan Publish ke GitHub Release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          # Ambil baris pertama saja untuk menghindari error JSON
          CLEAN_MSG=$(echo "$COMMIT_MSG" | head -n 1)

          cat <<EOF > update-config.json
          {
            "releaseInfo": {
              "releaseNotes": "Update: $CLEAN_MSG"
            },
            "publish": {
              "provider": "github",
              "releaseType": "release"
            }
          }
          EOF

          npm run dist -- --publish always -c update-config.json