name: Build and Release Electron App

# PENGATURAN: Jalan otomatis setiap kali ada push ke branch 'main'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest 
    permissions:
      contents: write 

    steps:
      - name: 1. Mendownload kode dari Repository
        uses: actions/checkout@v4

      - name: 2. Mempersiapkan Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: 3. Menginstall Dependencies
        run: npm install

      - name: 4. Build Aplikasi dan Publish ke GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         npm run dist -- --publish always -c "{\"releaseInfo\":{\"releaseNotes\":\"Update otomatis dari commit: $COMMIT_MSG\"},\"publish\":{\"releaseType\":\"release\"}}"