name: Build and Release Electron App

# PENGATURAN: Jalan otomatis setiap kali ada push ke branch 'main'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest 
    permissions:
      contents: write 

    steps:
      - name: 1. Mendownload kode dari Repository
        uses: actions/checkout@v4

      - name: 2. Mempersiapkan Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 3. Menginstall Dependencies
        run: npm install

      - name: 4. Build Aplikasi dan Publish ke GitHub Release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FULL_COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          # Skrip Python untuk membuang baris pertama dan mengambil sisanya
          SAFE_MSG=$(echo "$FULL_COMMIT_MSG" | python3 -c "import sys, json; lines = sys.stdin.readlines(); desc = ''.join(lines[1:]).strip(); print(json.dumps(desc).strip('\"'))")

          cat <<EOF > update-config.json
          {
            "releaseInfo": {
              "releaseNotes": "$SAFE_MSG"
            },
            "publish": {
              "provider": "github",
              "releaseType": "release"
            }
          }
          EOF

          npm run dist -- --publish always -c update-config.json